export interface UsEtfData {
  ticker: string;
  name: string;
  category: string;
  issuer: string;
  currency: 'USD';
  exchange: string;
  price: number;
  changePct: number;
  change: number;
  nav: number;
  aum: number;
  aumFormatted: string;
  volume: number;
  avgVolume: number;
  expenseRatio: number;
  dividendYield: number;
  distributionFrequency: 'Monthly' | 'Quarterly' | 'Semi-Annual' | 'Annual' | 'None' | string;
  beta: number;
  sharpeRatio: number;
  trackingError: number;
  return1y: number;
  return3y: number;
  return5y: number;
  inceptionDate: string;
  fiftyTwoWeekHigh: number;
  fiftyTwoWeekLow: number;
  benchmarkIndex: string;
  holdingsCount: number;
  topHoldings: Array<{ symbol: string; name: string; weight: number }>;
  sectorWeights: Array<{ sector: string; weight: number }>;
  description: string;
}

export const TOP_US_ETFS_SEED: UsEtfData[] = [
  // 1. BROAD MARKET & MEGA CAP INDEXES
  {
    ticker: 'SPY',
    name: 'SPDR S&P 500 ETF Trust',
    category: 'Broad Market',
    issuer: 'State Street Global Advisors',
    currency: 'USD',
    exchange: 'NYSE Arca',
    price: 588.42,
    changePct: 0.45,
    change: 2.64,
    nav: 588.39,
    aum: 564200000000,
    aumFormatted: '$564.2B',
    volume: 54200000,
    avgVolume: 58000000,
    expenseRatio: 0.09,
    dividendYield: 1.22,
    distributionFrequency: 'Quarterly',
    beta: 1.00,
    sharpeRatio: 1.42,
    trackingError: 0.03,
    return1y: 28.4,
    return3y: 11.2,
    return5y: 15.8,
    inceptionDate: '1993-01-22',
    fiftyTwoWeekHigh: 595.20,
    fiftyTwoWeekLow: 490.10,
    benchmarkIndex: 'S&P 500 Index',
    holdingsCount: 503,
    topHoldings: [
      { symbol: 'AAPL', name: 'Apple Inc.', weight: 7.15 },
      { symbol: 'MSFT', name: 'Microsoft Corp.', weight: 6.82 },
      { symbol: 'NVDA', name: 'NVIDIA Corp.', weight: 6.45 },
      { symbol: 'AMZN', name: 'Amazon.com Inc.', weight: 3.75 },
      { symbol: 'META', name: 'Meta Platforms Inc.', weight: 2.65 },
      { symbol: 'GOOGL', name: 'Alphabet Inc. Class A', weight: 2.15 },
      { symbol: 'BRK.B', name: 'Berkshire Hathaway', weight: 1.85 },
      { symbol: 'AVGO', name: 'Broadcom Inc.', weight: 1.75 },
      { symbol: 'TSLA', name: 'Tesla Inc.', weight: 1.62 },
      { symbol: 'JPM', name: 'JPMorgan Chase & Co.', weight: 1.45 }
    ],
    sectorWeights: [
      { sector: 'Technology', weight: 32.4 },
      { sector: 'Financials', weight: 13.2 },
      { sector: 'Healthcare', weight: 11.8 },
      { sector: 'Consumer Cyclical', weight: 10.4 },
      { sector: 'Communication Services', weight: 8.9 },
      { sector: 'Industrials', weight: 8.4 },
      { sector: 'Consumer Defensive', weight: 5.8 }
    ],
    description: 'Dünyanın ilk ve en likit borsa yatırım fonudur. S&P 500 endeksindeki en büyük 500 Amerikan şirketini birebir takip eder.'
  },
  {
    ticker: 'VOO',
    name: 'Vanguard S&P 500 ETF',
    category: 'Broad Market',
    issuer: 'Vanguard',
    currency: 'USD',
    exchange: 'NYSE Arca',
    price: 540.18,
    changePct: 0.44,
    change: 2.37,
    nav: 540.15,
    aum: 492800000000,
    aumFormatted: '$492.8B',
    volume: 5120000,
    avgVolume: 5600000,
    expenseRatio: 0.03,
    dividendYield: 1.26,
    distributionFrequency: 'Quarterly',
    beta: 1.00,
    sharpeRatio: 1.45,
    trackingError: 0.01,
    return1y: 28.5,
    return3y: 11.3,
    return5y: 15.9,
    inceptionDate: '2010-09-07',
    fiftyTwoWeekHigh: 546.80,
    fiftyTwoWeekLow: 450.20,
    benchmarkIndex: 'S&P 500 Index',
    holdingsCount: 504,
    topHoldings: [
      { symbol: 'AAPL', name: 'Apple Inc.', weight: 7.18 },
      { symbol: 'MSFT', name: 'Microsoft Corp.', weight: 6.84 },
      { symbol: 'NVDA', name: 'NVIDIA Corp.', weight: 6.47 },
      { symbol: 'AMZN', name: 'Amazon.com Inc.', weight: 3.76 },
      { symbol: 'META', name: 'Meta Platforms Inc.', weight: 2.66 },
      { symbol: 'GOOGL', name: 'Alphabet Inc.', weight: 2.16 },
      { symbol: 'BRK.B', name: 'Berkshire Hathaway', weight: 1.86 },
      { symbol: 'AVGO', name: 'Broadcom Inc.', weight: 1.76 }
    ],
    sectorWeights: [
      { sector: 'Technology', weight: 32.5 },
      { sector: 'Financials', weight: 13.1 },
      { sector: 'Healthcare', weight: 11.9 }
    ],
    description: '%0.03 ultra düşük masraf oranı ile uzun vadeli yatırımcılar için en popüler S&P 500 endeks fonudur.'
  },
  {
    ticker: 'IVV',
    name: 'iShares Core S&P 500 ETF',
    category: 'Broad Market',
    issuer: 'BlackRock / iShares',
    currency: 'USD',
    exchange: 'NYSE Arca',
    price: 590.25,
    changePct: 0.46,
    change: 2.70,
    nav: 590.22,
    aum: 485100000000,
    aumFormatted: '$485.1B',
    volume: 4850000,
    avgVolume: 5200000,
    expenseRatio: 0.03,
    dividendYield: 1.25,
    distributionFrequency: 'Quarterly',
    beta: 1.00,
    sharpeRatio: 1.44,
    trackingError: 0.02,
    return1y: 28.6,
    return3y: 11.3,
    return5y: 15.9,
    inceptionDate: '2000-05-15',
    fiftyTwoWeekHigh: 597.50,
    fiftyTwoWeekLow: 492.00,
    benchmarkIndex: 'S&P 500 Index',
    holdingsCount: 503,
    topHoldings: [
      { symbol: 'AAPL', name: 'Apple Inc.', weight: 7.16 },
      { symbol: 'MSFT', name: 'Microsoft Corp.', weight: 6.83 },
      { symbol: 'NVDA', name: 'NVIDIA Corp.', weight: 6.46 }
    ],
    sectorWeights: [
      { sector: 'Technology', weight: 32.5 },
      { sector: 'Financials', weight: 13.2 }
    ],
    description: 'BlackRock iShares tarafından sunulan düşük maliyetli temel S&P 500 borsa yatırım fonu.'
  },
  {
    ticker: 'QQQ',
    name: 'Invesco QQQ Trust (NASDAQ 100)',
    category: 'Technology',
    issuer: 'Invesco',
    currency: 'USD',
    exchange: 'NASDAQ',
    price: 498.65,
    changePct: 0.82,
    change: 4.05,
    nav: 498.60,
    aum: 285400000000,
    aumFormatted: '$285.4B',
    volume: 38500000,
    avgVolume: 42000000,
    expenseRatio: 0.20,
    dividendYield: 0.58,
    distributionFrequency: 'Quarterly',
    beta: 1.18,
    sharpeRatio: 1.58,
    trackingError: 0.04,
    return1y: 35.8,
    return3y: 12.8,
    return5y: 20.4,
    inceptionDate: '1999-03-10',
    fiftyTwoWeekHigh: 508.20,
    fiftyTwoWeekLow: 395.40,
    benchmarkIndex: 'NASDAQ-100 Index',
    holdingsCount: 101,
    topHoldings: [
      { symbol: 'AAPL', name: 'Apple Inc.', weight: 9.15 },
      { symbol: 'MSFT', name: 'Microsoft Corp.', weight: 8.42 },
      { symbol: 'NVDA', name: 'NVIDIA Corp.', weight: 8.10 },
      { symbol: 'AMZN', name: 'Amazon.com Inc.', weight: 5.25 },
      { symbol: 'META', name: 'Meta Platforms Inc.', weight: 4.85 },
      { symbol: 'AVGO', name: 'Broadcom Inc.', weight: 4.15 },
      { symbol: 'GOOGL', name: 'Alphabet Inc.', weight: 3.10 },
      { symbol: 'TSLA', name: 'Tesla Inc.', weight: 2.95 },
      { symbol: 'COST', name: 'Costco Wholesale', weight: 2.65 },
      { symbol: 'AMD', name: 'Advanced Micro Devices', weight: 1.95 }
    ],
    sectorWeights: [
      { sector: 'Technology', weight: 51.4 },
      { sector: 'Communication Services', weight: 15.6 },
      { sector: 'Consumer Cyclical', weight: 13.8 },
      { sector: 'Healthcare', weight: 6.2 },
      { sector: 'Industrials', weight: 4.8 }
    ],
    description: 'Dünyanın en yenilikçi 100 finans dışı teknoloji ve büyüme devini içeren NASDAQ-100 endeksinin öncü borsa yatırım fonu.'
  },
  {
    ticker: 'VTI',
    name: 'Vanguard Total Stock Market ETF',
    category: 'Broad Market',
    issuer: 'Vanguard',
    currency: 'USD',
    exchange: 'NYSE Arca',
    price: 284.90,
    changePct: 0.40,
    change: 1.14,
    nav: 284.88,
    aum: 412500000000,
    aumFormatted: '$412.5B',
    volume: 3200000,
    avgVolume: 3500000,
    expenseRatio: 0.03,
    dividendYield: 1.31,
    distributionFrequency: 'Quarterly',
    beta: 1.02,
    sharpeRatio: 1.38,
    trackingError: 0.02,
    return1y: 27.2,
    return3y: 10.4,
    return5y: 14.8,
    inceptionDate: '2001-05-24',
    fiftyTwoWeekHigh: 289.40,
    fiftyTwoWeekLow: 235.10,
    benchmarkIndex: 'CRSP US Total Market Index',
    holdingsCount: 3680,
    topHoldings: [
      { symbol: 'AAPL', name: 'Apple Inc.', weight: 6.25 },
      { symbol: 'MSFT', name: 'Microsoft Corp.', weight: 5.95 },
      { symbol: 'NVDA', name: 'NVIDIA Corp.', weight: 5.62 },
      { symbol: 'AMZN', name: 'Amazon.com Inc.', weight: 3.25 },
      { symbol: 'META', name: 'Meta Platforms Inc.', weight: 2.30 }
    ],
    sectorWeights: [
      { sector: 'Technology', weight: 30.5 },
      { sector: 'Financials', weight: 13.8 },
      { sector: 'Healthcare', weight: 11.6 },
      { sector: 'Industrials', weight: 9.8 }
    ],
    description: 'Büyük, orta, küçük ve mikro ölçekli yaklaşık 3.700 Amerikan şirketinin tamamını kapsayan tüm ABD hisse senedi piyasası fonu.'
  },
  {
    ticker: 'DIA',
    name: 'SPDR Dow Jones Industrial Average ETF',
    category: 'Broad Market',
    issuer: 'State Street Global Advisors',
    currency: 'USD',
    exchange: 'NYSE Arca',
    price: 438.10,
    changePct: 0.28,
    change: 1.22,
    nav: 438.05,
    aum: 34800000000,
    aumFormatted: '$34.8B',
    volume: 3100000,
    avgVolume: 3400000,
    expenseRatio: 0.16,
    dividendYield: 1.62,
    distributionFrequency: 'Monthly',
    beta: 0.88,
    sharpeRatio: 1.28,
    trackingError: 0.04,
    return1y: 22.4,
    return3y: 9.8,
    return5y: 12.6,
    inceptionDate: '1998-01-14',
    fiftyTwoWeekHigh: 445.00,
    fiftyTwoWeekLow: 372.50,
    benchmarkIndex: 'Dow Jones Industrial Average',
    holdingsCount: 30,
    topHoldings: [
      { symbol: 'UNH', name: 'UnitedHealth Group Inc.', weight: 9.15 },
      { symbol: 'GS', name: 'Goldman Sachs Group Inc.', weight: 8.25 },
      { symbol: 'MSFT', name: 'Microsoft Corp.', weight: 6.85 },
      { symbol: 'HD', name: 'Home Depot Inc.', weight: 5.95 },
      { symbol: 'CAT', name: 'Caterpillar Inc.', weight: 5.45 }
    ],
    sectorWeights: [
      { sector: 'Financials', weight: 23.4 },
      { sector: 'Healthcare', weight: 19.8 },
      { sector: 'Industrials', weight: 15.2 },
      { sector: 'Technology', weight: 14.6 }
    ],
    description: 'Amerikan sanayisinin ve ekonomisinin temelini oluşturan 30 mega köklü mavi çip şirketi takip eden fon.'
  },
  {
    ticker: 'IWM',
    name: 'iShares Russell 2000 ETF',
    category: 'Broad Market',
    issuer: 'BlackRock / iShares',
    currency: 'USD',
    exchange: 'NYSE Arca',
    price: 228.40,
    changePct: 0.95,
    change: 2.15,
    nav: 228.35,
    aum: 68500000000,
    aumFormatted: '$68.5B',
    volume: 24500000,
    avgVolume: 28000000,
    expenseRatio: 0.19,
    dividendYield: 1.35,
    distributionFrequency: 'Quarterly',
    beta: 1.25,
    sharpeRatio: 0.95,
    trackingError: 0.05,
    return1y: 24.8,
    return3y: 4.8,
    return5y: 9.2,
    inceptionDate: '2000-05-22',
    fiftyTwoWeekHigh: 235.80,
    fiftyTwoWeekLow: 188.20,
    benchmarkIndex: 'Russell 2000 Index',
    holdingsCount: 1985,
    topHoldings: [
      { symbol: 'FTAI', name: 'FTAI Aviation Ltd.', weight: 0.65 },
      { symbol: 'SPSN', name: 'Sprouts Farmers Market', weight: 0.58 },
      { symbol: 'VRT', name: 'Vertiv Holdings Co.', weight: 0.54 }
    ],
    sectorWeights: [
      { sector: 'Financials', weight: 18.2 },
      { sector: 'Industrials', weight: 17.5 },
      { sector: 'Healthcare', weight: 15.1 },
      { sector: 'Technology', weight: 13.9 }
    ],
    description: 'ABD küçük ölçekli (Small-Cap) şirketlerin amiral gemisi göstergesi olan Russell 2000 endeks fonu.'
  },

  // 2. SECTOR & SEMICONDUCTOR LEADERS
  {
    ticker: 'XLK',
    name: 'Technology Select Sector SPDR Fund',
    category: 'Technology',
    issuer: 'State Street Global Advisors',
    currency: 'USD',
    exchange: 'NYSE Arca',
    price: 232.50,
    changePct: 1.15,
    change: 2.64,
    nav: 232.45,
    aum: 72400000000,
    aumFormatted: '$72.4B',
    volume: 8500000,
    avgVolume: 9200000,
    expenseRatio: 0.09,
    dividendYield: 0.65,
    distributionFrequency: 'Quarterly',
    beta: 1.22,
    sharpeRatio: 1.62,
    trackingError: 0.03,
    return1y: 36.5,
    return3y: 15.4,
    return5y: 23.8,
    inceptionDate: '1998-12-16',
    fiftyTwoWeekHigh: 240.20,
    fiftyTwoWeekLow: 180.50,
    benchmarkIndex: 'Technology Select Sector Index',
    holdingsCount: 68,
    topHoldings: [
      { symbol: 'NVDA', name: 'NVIDIA Corp.', weight: 16.4 },
      { symbol: 'AAPL', name: 'Apple Inc.', weight: 15.2 },
      { symbol: 'MSFT', name: 'Microsoft Corp.', weight: 14.8 },
      { symbol: 'AVGO', name: 'Broadcom Inc.', weight: 5.6 },
      { symbol: 'ORCL', name: 'Oracle Corp.', weight: 3.4 }
    ],
    sectorWeights: [
      { sector: 'Semiconductors', weight: 34.5 },
      { sector: 'Software', weight: 31.8 },
      { sector: 'Technology Hardware', weight: 22.4 }
    ],
    description: 'S&P 500 teknoloji sektörünün çekirdek şirketlerine odaklanan sektör lideri fon.'
  },
  {
    ticker: 'SOXX',
    name: 'iShares Semiconductor ETF',
    category: 'Technology',
    issuer: 'BlackRock / iShares',
    currency: 'USD',
    exchange: 'NASDAQ',
    price: 242.80,
    changePct: 1.85,
    change: 4.41,
    nav: 242.75,
    aum: 16800000000,
    aumFormatted: '$16.8B',
    volume: 1200000,
    avgVolume: 1400000,
    expenseRatio: 0.35,
    dividendYield: 0.72,
    distributionFrequency: 'Quarterly',
    beta: 1.48,
    sharpeRatio: 1.65,
    trackingError: 0.06,
    return1y: 44.2,
    return3y: 18.5,
    return5y: 28.9,
    inceptionDate: '2001-07-10',
    fiftyTwoWeekHigh: 265.40,
    fiftyTwoWeekLow: 175.20,
    benchmarkIndex: 'NYSE Semiconductor Index',
    holdingsCount: 30,
    topHoldings: [
      { symbol: 'NVDA', name: 'NVIDIA Corp.', weight: 9.85 },
      { symbol: 'AVGO', name: 'Broadcom Inc.', weight: 8.75 },
      { symbol: 'AMD', name: 'Advanced Micro Devices', weight: 7.25 },
      { symbol: 'QCOM', name: 'Qualcomm Inc.', weight: 6.85 },
      { symbol: 'TSM', name: 'Taiwan Semiconductor ADR', weight: 4.95 }
    ],
    sectorWeights: [
      { sector: 'Semiconductors & Chip Design', weight: 82.5 },
      { sector: 'Semiconductor Equipment', weight: 17.5 }
    ],
    description: 'Yapay zeka çipleri ve yarı iletken tasarım/üretim devlerine yatırım yapan popüler yarı iletken fonu.'
  },
  {
    ticker: 'SMH',
    name: 'VanEck Semiconductor ETF',
    category: 'Technology',
    issuer: 'VanEck',
    currency: 'USD',
    exchange: 'NASDAQ',
    price: 265.40,
    changePct: 1.92,
    change: 5.00,
    nav: 265.35,
    aum: 24500000000,
    aumFormatted: '$24.5B',
    volume: 5800000,
    avgVolume: 6200000,
    expenseRatio: 0.35,
    dividendYield: 0.52,
    distributionFrequency: 'Annual',
    beta: 1.52,
    sharpeRatio: 1.72,
    trackingError: 0.05,
    return1y: 48.6,
    return3y: 21.4,
    return5y: 31.2,
    inceptionDate: '2011-12-20',
    fiftyTwoWeekHigh: 282.50,
    fiftyTwoWeekLow: 182.10,
    benchmarkIndex: 'MVIS US Listed Semiconductor 25 Index',
    holdingsCount: 26,
    topHoldings: [
      { symbol: 'NVDA', name: 'NVIDIA Corp.', weight: 20.4 },
      { symbol: 'TSM', name: 'Taiwan Semiconductor ADR', weight: 12.8 },
      { symbol: 'AVGO', name: 'Broadcom Inc.', weight: 7.6 },
      { symbol: 'ASML', name: 'ASML Holding NV', weight: 5.8 },
      { symbol: 'AMD', name: 'Advanced Micro Devices', weight: 5.4 }
    ],
    sectorWeights: [
      { sector: 'Semiconductor Manufacturing', weight: 58.4 },
      { sector: 'Semiconductor Equipment', weight: 41.6 }
    ],
    description: 'Nvidia ve TSMC gibi küresel yarı iletken tekel ve ekipman üreticilerini yüksek konsantrasyonla tutan en yüksek getirili fonlardan biri.'
  },
  {
    ticker: 'XLF',
    name: 'Financial Select Sector SPDR Fund',
    category: 'Broad Market',
    issuer: 'State Street Global Advisors',
    currency: 'USD',
    exchange: 'NYSE Arca',
    price: 49.20,
    changePct: 0.35,
    change: 0.17,
    nav: 49.18,
    aum: 43800000000,
    aumFormatted: '$43.8B',
    volume: 38000000,
    avgVolume: 41000000,
    expenseRatio: 0.09,
    dividendYield: 1.54,
    distributionFrequency: 'Quarterly',
    beta: 0.98,
    sharpeRatio: 1.35,
    trackingError: 0.03,
    return1y: 33.2,
    return3y: 11.8,
    return5y: 13.5,
    inceptionDate: '1998-12-16',
    fiftyTwoWeekHigh: 50.80,
    fiftyTwoWeekLow: 37.20,
    benchmarkIndex: 'Financial Select Sector Index',
    holdingsCount: 72,
    topHoldings: [
      { symbol: 'BRK.B', name: 'Berkshire Hathaway', weight: 13.8 },
      { symbol: 'JPM', name: 'JPMorgan Chase & Co.', weight: 10.2 },
      { symbol: 'V', name: 'Visa Inc.', weight: 7.9 },
      { symbol: 'MA', name: 'Mastercard Inc.', weight: 6.8 },
      { symbol: 'BAC', name: 'Bank of America', weight: 4.8 }
    ],
    sectorWeights: [
      { sector: 'Diversified Financials', weight: 36.5 },
      { sector: 'Banks', weight: 30.2 },
      { sector: 'Insurance', weight: 20.4 }
    ],
    description: 'JPMorgan, Berkshire Hathaway ve Visa gibi ABD finans ve bankacılık devlerini kapsayan fon.'
  },
  {
    ticker: 'XLE',
    name: 'Energy Select Sector SPDR Fund',
    category: 'Commodities',
    issuer: 'State Street Global Advisors',
    currency: 'USD',
    exchange: 'NYSE Arca',
    price: 92.40,
    changePct: -0.42,
    change: -0.39,
    nav: 92.38,
    aum: 37200000000,
    aumFormatted: '$37.2B',
    volume: 14200000,
    avgVolume: 16000000,
    expenseRatio: 0.09,
    dividendYield: 3.18,
    distributionFrequency: 'Quarterly',
    beta: 0.72,
    sharpeRatio: 0.92,
    trackingError: 0.04,
    return1y: 8.5,
    return3y: 16.8,
    return5y: 24.2,
    inceptionDate: '1998-12-16',
    fiftyTwoWeekHigh: 98.50,
    fiftyTwoWeekLow: 82.10,
    benchmarkIndex: 'Energy Select Sector Index',
    holdingsCount: 23,
    topHoldings: [
      { symbol: 'XOM', name: 'Exxon Mobil Corp.', weight: 22.8 },
      { symbol: 'CVX', name: 'Chevron Corp.', weight: 16.5 },
      { symbol: 'EOG', name: 'EOG Resources Inc.', weight: 4.9 },
      { symbol: 'COP', name: 'ConocoPhillips', weight: 8.4 }
    ],
    sectorWeights: [
      { sector: 'Oil, Gas & Consumable Fuels', weight: 89.2 },
      { sector: 'Energy Equipment & Services', weight: 10.8 }
    ],
    description: 'ExxonMobil ve Chevron başta olmak üzere ABD petrol ve enerji sektörünün lider fonudur.'
  },
  {
    ticker: 'XLV',
    name: 'Health Care Select Sector SPDR Fund',
    category: 'Broad Market',
    issuer: 'State Street Global Advisors',
    currency: 'USD',
    exchange: 'NYSE Arca',
    price: 151.20,
    changePct: 0.15,
    change: 0.23,
    nav: 151.15,
    aum: 40500000000,
    aumFormatted: '$40.5B',
    volume: 7800000,
    avgVolume: 8500000,
    expenseRatio: 0.09,
    dividendYield: 1.58,
    distributionFrequency: 'Quarterly',
    beta: 0.68,
    sharpeRatio: 1.12,
    trackingError: 0.02,
    return1y: 16.4,
    return3y: 6.8,
    return5y: 10.8,
    inceptionDate: '1998-12-16',
    fiftyTwoWeekHigh: 156.40,
    fiftyTwoWeekLow: 132.80,
    benchmarkIndex: 'Health Care Select Sector Index',
    holdingsCount: 64,
    topHoldings: [
      { symbol: 'LLY', name: 'Eli Lilly & Co.', weight: 11.2 },
      { symbol: 'UNH', name: 'UnitedHealth Group', weight: 9.8 },
      { symbol: 'JNJ', name: 'Johnson & Johnson', weight: 7.2 },
      { symbol: 'ABBV', name: 'AbbVie Inc.', weight: 6.4 }
    ],
    sectorWeights: [
      { sector: 'Pharmaceuticals', weight: 32.5 },
      { sector: 'Health Care Providers', weight: 24.8 },
      { sector: 'Biotechnology', weight: 18.2 }
    ],
    description: 'Eli Lilly, UnitedHealth ve Johnson & Johnson gibi sağlık, biyoteknoloji ve ilaç devlerini içerir.'
  },

  // 3. DIVIDENDS & HIGH CASH FLOW
  {
    ticker: 'SCHD',
    name: 'Schwab U.S. Dividend Equity ETF',
    category: 'Dividends',
    issuer: 'Charles Schwab',
    currency: 'USD',
    exchange: 'NYSE Arca',
    price: 84.60,
    changePct: 0.32,
    change: 0.27,
    nav: 84.58,
    aum: 58900000000,
    aumFormatted: '$58.9B',
    volume: 3800000,
    avgVolume: 4200000,
    expenseRatio: 0.06,
    dividendYield: 3.42,
    distributionFrequency: 'Quarterly',
    beta: 0.78,
    sharpeRatio: 1.25,
    trackingError: 0.03,
    return1y: 18.2,
    return3y: 8.5,
    return5y: 12.8,
    inceptionDate: '2011-10-20',
    fiftyTwoWeekHigh: 86.20,
    fiftyTwoWeekLow: 71.40,
    benchmarkIndex: 'Dow Jones U.S. Dividend 100 Index',
    holdingsCount: 104,
    topHoldings: [
      { symbol: 'CSCO', name: 'Cisco Systems Inc.', weight: 4.45 },
      { symbol: 'ABBV', name: 'AbbVie Inc.', weight: 4.38 },
      { symbol: 'HD', name: 'Home Depot Inc.', weight: 4.25 },
      { symbol: 'TXN', name: 'Texas Instruments', weight: 4.10 },
      { symbol: 'CVX', name: 'Chevron Corp.', weight: 4.02 },
      { symbol: 'AMGN', name: 'Amgen Inc.', weight: 3.95 },
      { symbol: 'PEP', name: 'PepsiCo Inc.', weight: 3.85 }
    ],
    sectorWeights: [
      { sector: 'Financials', weight: 17.8 },
      { sector: 'Healthcare', weight: 16.2 },
      { sector: 'Consumer Defensive', weight: 14.5 },
      { sector: 'Industrials', weight: 13.8 },
      { sector: 'Technology', weight: 11.2 }
    ],
    description: 'Düzenli temettü ödeyen, güçlü nakit akışına ve yüksek özsermaye karlılığına sahip 100 kaliteli ABD temettü hissesi fonu.'
  },
  {
    ticker: 'JEPI',
    name: 'JPMorgan Equity Premium Income ETF',
    category: 'Dividends',
    issuer: 'JPMorgan Chase',
    currency: 'USD',
    exchange: 'NYSE Arca',
    price: 58.75,
    changePct: 0.18,
    change: 0.11,
    nav: 58.72,
    aum: 36200000000,
    aumFormatted: '$36.2B',
    volume: 4500000,
    avgVolume: 5100000,
    expenseRatio: 0.35,
    dividendYield: 7.25,
    distributionFrequency: 'Monthly',
    beta: 0.62,
    sharpeRatio: 1.38,
    trackingError: 0.08,
    return1y: 15.6,
    return3y: 8.9,
    return5y: 11.4,
    inceptionDate: '2020-05-20',
    fiftyTwoWeekHigh: 60.10,
    fiftyTwoWeekLow: 53.20,
    benchmarkIndex: 'S&P 500 Total Return Index',
    holdingsCount: 135,
    topHoldings: [
      { symbol: 'MSFT', name: 'Microsoft Corp.', weight: 1.85 },
      { symbol: 'AAPL', name: 'Apple Inc.', weight: 1.75 },
      { symbol: 'AMZN', name: 'Amazon.com Inc.', weight: 1.65 },
      { symbol: 'UNH', name: 'UnitedHealth Group', weight: 1.55 }
    ],
    sectorWeights: [
      { sector: 'Technology', weight: 18.2 },
      { sector: 'Healthcare', weight: 14.5 },
      { sector: 'Financials', weight: 13.8 }
    ],
    description: 'Aylık yüksek temettü ödemesi hedefleyen, hisse senedi portföyü ve opsiyon prim geliri (Covered Call) stratejisi sunan JPMorgan fonu.'
  },
  {
    ticker: 'JEPQ',
    name: 'JPMorgan Nasdaq Equity Premium Income ETF',
    category: 'Dividends',
    issuer: 'JPMorgan Chase',
    currency: 'USD',
    exchange: 'NASDAQ',
    price: 55.40,
    changePct: 0.45,
    change: 0.25,
    nav: 55.38,
    aum: 18400000000,
    aumFormatted: '$18.4B',
    volume: 3800000,
    avgVolume: 4200000,
    expenseRatio: 0.35,
    dividendYield: 9.15,
    distributionFrequency: 'Monthly',
    beta: 0.78,
    sharpeRatio: 1.45,
    trackingError: 0.09,
    return1y: 22.8,
    return3y: 14.2,
    return5y: 17.5,
    inceptionDate: '2022-05-03',
    fiftyTwoWeekHigh: 56.80,
    fiftyTwoWeekLow: 47.50,
    benchmarkIndex: 'Nasdaq-100 Index',
    holdingsCount: 95,
    topHoldings: [
      { symbol: 'AAPL', name: 'Apple Inc.', weight: 7.2 },
      { symbol: 'MSFT', name: 'Microsoft Corp.', weight: 6.8 },
      { symbol: 'NVDA', name: 'NVIDIA Corp.', weight: 6.4 },
      { symbol: 'AMZN', name: 'Amazon.com Inc.', weight: 4.8 }
    ],
    sectorWeights: [
      { sector: 'Technology', weight: 48.5 },
      { sector: 'Communication Services', weight: 16.2 }
    ],
    description: 'Nasdaq-100 teknoloji hisseleri ve opsiyon satış primleriyle aylık %9+ efektif getiri sunan büyüme + temettü fonu.'
  },
  {
    ticker: 'VIG',
    name: 'Vanguard Dividend Appreciation ETF',
    category: 'Dividends',
    issuer: 'Vanguard',
    currency: 'USD',
    exchange: 'NYSE Arca',
    price: 198.50,
    changePct: 0.35,
    change: 0.69,
    nav: 198.45,
    aum: 85200000000,
    aumFormatted: '$85.2B',
    volume: 1200000,
    avgVolume: 1400000,
    expenseRatio: 0.06,
    dividendYield: 1.75,
    distributionFrequency: 'Quarterly',
    beta: 0.84,
    sharpeRatio: 1.36,
    trackingError: 0.02,
    return1y: 24.2,
    return3y: 10.2,
    return5y: 13.8,
    inceptionDate: '2006-04-21',
    fiftyTwoWeekHigh: 202.40,
    fiftyTwoWeekLow: 165.20,
    benchmarkIndex: 'S&P U.S. Dividend Growers Index',
    holdingsCount: 338,
    topHoldings: [
      { symbol: 'MSFT', name: 'Microsoft Corp.', weight: 5.6 },
      { symbol: 'AAPL', name: 'Apple Inc.', weight: 4.8 },
      { symbol: 'JPM', name: 'JPMorgan Chase', weight: 4.1 },
      { symbol: 'AVGO', name: 'Broadcom Inc.', weight: 3.9 }
    ],
    sectorWeights: [
      { sector: 'Technology', weight: 24.2 },
      { sector: 'Financials', weight: 21.5 },
      { sector: 'Healthcare', weight: 14.8 }
    ],
    description: 'En az 10 yıl üst üste temettüsünü artıran kaliteli Amerikan devlerini içeren temettü büyüme fonu.'
  },

  // 4. FIXED INCOME & TREASURIES
  {
    ticker: 'TLT',
    name: 'iShares 20+ Year Treasury Bond ETF',
    category: 'Fixed Income',
    issuer: 'BlackRock / iShares',
    currency: 'USD',
    exchange: 'NASDAQ',
    price: 98.40,
    changePct: -0.25,
    change: -0.25,
    nav: 98.38,
    aum: 52400000000,
    aumFormatted: '$52.4B',
    volume: 38000000,
    avgVolume: 42000000,
    expenseRatio: 0.15,
    dividendYield: 4.15,
    distributionFrequency: 'Monthly',
    beta: -0.32,
    sharpeRatio: 0.42,
    trackingError: 0.04,
    return1y: 6.8,
    return3y: -8.4,
    return5y: -6.5,
    inceptionDate: '2002-07-22',
    fiftyTwoWeekHigh: 101.50,
    fiftyTwoWeekLow: 86.80,
    benchmarkIndex: 'ICE U.S. Treasury 20+ Year Bond Index',
    holdingsCount: 42,
    topHoldings: [
      { symbol: 'US-T-20Y', name: 'US Treasury 20Y Bond', weight: 28.5 },
      { symbol: 'US-T-30Y', name: 'US Treasury 30Y Bond', weight: 71.5 }
    ],
    sectorWeights: [
      { sector: 'US Government Sovereign Bonds', weight: 100.0 }
    ],
    description: 'FED faiz kararları ve uzun vadeli ABD hazine tahvillerine (20+ Yıl) yatırım yapan en likit tahvil fonudur.'
  },
  {
    ticker: 'BND',
    name: 'Vanguard Total Bond Market ETF',
    category: 'Fixed Income',
    issuer: 'Vanguard',
    currency: 'USD',
    exchange: 'NASDAQ',
    price: 74.20,
    changePct: 0.08,
    change: 0.06,
    nav: 74.18,
    aum: 110400000000,
    aumFormatted: '$110.4B',
    volume: 7200000,
    avgVolume: 7800000,
    expenseRatio: 0.03,
    dividendYield: 3.85,
    distributionFrequency: 'Monthly',
    beta: 0.12,
    sharpeRatio: 0.65,
    trackingError: 0.02,
    return1y: 8.2,
    return3y: 0.8,
    return5y: 0.4,
    inceptionDate: '2007-04-03',
    fiftyTwoWeekHigh: 75.80,
    fiftyTwoWeekLow: 69.80,
    benchmarkIndex: 'Bloomberg U.S. Aggregate Float Adjusted Index',
    holdingsCount: 11200,
    topHoldings: [
      { symbol: 'UST', name: 'US Treasury Bonds', weight: 68.2 },
      { symbol: 'CORP', name: 'Investment Grade Corporate', weight: 26.5 }
    ],
    sectorWeights: [
      { sector: 'Government', weight: 68.2 },
      { sector: 'Corporate', weight: 26.5 },
      { sector: 'Securitized', weight: 5.3 }
    ],
    description: 'ABD yatırım yapılabilir seviyedeki tüm kamu ve özel sektör tahvillerini içeren 110 milyar dolarlık dev tahvil fonu.'
  },

  // 5. COMMODITIES & PRECIOUS METALS
  {
    ticker: 'GLD',
    name: 'SPDR Gold Shares',
    category: 'Commodities',
    issuer: 'State Street Global Advisors',
    currency: 'USD',
    exchange: 'NYSE Arca',
    price: 246.80,
    changePct: 0.65,
    change: 1.59,
    nav: 246.75,
    aum: 68500000000,
    aumFormatted: '$68.5B',
    volume: 7500000,
    avgVolume: 8200000,
    expenseRatio: 0.40,
    dividendYield: 0.00,
    distributionFrequency: 'Annual',
    beta: 0.08,
    sharpeRatio: 1.48,
    trackingError: 0.05,
    return1y: 38.4,
    return3y: 14.8,
    return5y: 11.2,
    inceptionDate: '2004-11-18',
    fiftyTwoWeekHigh: 252.80,
    fiftyTwoWeekLow: 182.40,
    benchmarkIndex: 'LBMA Gold Price PM (USD)',
    holdingsCount: 1,
    topHoldings: [
      { symbol: 'GOLD', name: 'Physical Gold Bullion', weight: 100.0 }
    ],
    sectorWeights: [
      { sector: 'Physical Gold Vaults', weight: 100.0 }
    ],
    description: 'Londra kasalarında fiziksel olarak saklanan altın külçelerine birebir dayalı dünyanın en büyük emtia fonudur.'
  },
  {
    ticker: 'SLV',
    name: 'iShares Silver Trust',
    category: 'Commodities',
    issuer: 'BlackRock / iShares',
    currency: 'USD',
    exchange: 'NYSE Arca',
    price: 30.85,
    changePct: 1.15,
    change: 0.35,
    nav: 30.82,
    aum: 12400000000,
    aumFormatted: '$12.4B',
    volume: 21000000,
    avgVolume: 24000000,
    expenseRatio: 0.50,
    dividendYield: 0.00,
    distributionFrequency: 'Annual',
    beta: 0.35,
    sharpeRatio: 1.22,
    trackingError: 0.08,
    return1y: 42.5,
    return3y: 16.2,
    return5y: 12.4,
    inceptionDate: '2006-04-21',
    fiftyTwoWeekHigh: 32.80,
    fiftyTwoWeekLow: 20.40,
    benchmarkIndex: 'LBMA Silver Price',
    holdingsCount: 1,
    topHoldings: [
      { symbol: 'SILVER', name: 'Physical Silver Bullion', weight: 100.0 }
    ],
    sectorWeights: [
      { sector: 'Physical Silver', weight: 100.0 }
    ],
    description: 'Fiziksel gümüşe yatırım yapan en büyük küresel borsa yatırım fonu.'
  },

  // 6. CRYPTO & SPOT ETFS
  {
    ticker: 'IBIT',
    name: 'iShares Bitcoin Trust ETF',
    category: 'Crypto',
    issuer: 'BlackRock / iShares',
    currency: 'USD',
    exchange: 'NASDAQ',
    price: 52.40,
    changePct: 3.45,
    change: 1.75,
    nav: 52.38,
    aum: 22800000000,
    aumFormatted: '$22.8B',
    volume: 34000000,
    avgVolume: 39000000,
    expenseRatio: 0.25,
    dividendYield: 0.00,
    distributionFrequency: 'Annual',
    beta: 2.15,
    sharpeRatio: 1.85,
    trackingError: 0.12,
    return1y: 84.5,
    return3y: 45.2,
    return5y: 52.8,
    inceptionDate: '2024-01-11',
    fiftyTwoWeekHigh: 58.20,
    fiftyTwoWeekLow: 24.10,
    benchmarkIndex: 'CME CF Bitcoin Reference Rate - New York Variant',
    holdingsCount: 1,
    topHoldings: [
      { symbol: 'BTC', name: 'Physical Bitcoin (Coinbase Custody)', weight: 100.0 }
    ],
    sectorWeights: [
      { sector: 'Spot Bitcoin', weight: 100.0 }
    ],
    description: 'BlackRock tarafından ihraç edilen, doğrudan fiziksel Bitcoin rezervlerine dayalı spot kripto ETF.'
  },

  // 7. THEMATIC & GROWTH
  {
    ticker: 'ARKK',
    name: 'ARK Innovation ETF',
    category: 'Thematic & Growth',
    issuer: 'ARK Invest (Cathie Wood)',
    currency: 'USD',
    exchange: 'NYSE Arca',
    price: 49.50,
    changePct: 1.75,
    change: 0.85,
    nav: 49.45,
    aum: 6500000000,
    aumFormatted: '$6.5B',
    volume: 8500000,
    avgVolume: 9800000,
    expenseRatio: 0.75,
    dividendYield: 0.00,
    distributionFrequency: 'Annual',
    beta: 1.85,
    sharpeRatio: 0.65,
    trackingError: 0.15,
    return1y: 26.4,
    return3y: -14.2,
    return5y: -8.5,
    inceptionDate: '2014-10-31',
    fiftyTwoWeekHigh: 54.80,
    fiftyTwoWeekLow: 37.20,
    benchmarkIndex: 'MSCI World Index',
    holdingsCount: 35,
    topHoldings: [
      { symbol: 'TSLA', name: 'Tesla Inc.', weight: 11.8 },
      { symbol: 'ROKU', name: 'Roku Inc.', weight: 8.5 },
      { symbol: 'COIN', name: 'Coinbase Global Inc.', weight: 7.8 },
      { symbol: 'SQ', name: 'Block Inc.', weight: 6.9 },
      { symbol: 'PATH', name: 'UiPath Inc.', weight: 5.4 }
    ],
    sectorWeights: [
      { sector: 'Disruptive Innovation', weight: 45.2 },
      { sector: 'Genomics & AI', weight: 32.8 },
      { sector: 'Fintech & Web3', weight: 22.0 }
    ],
    description: 'Yıkıcı inovasyon, yapay zeka, otonom teknolojiler ve genomik alanlarına odaklanan aktif yönetimli büyüme fonu.'
  },
  {
    ticker: 'BOTZ',
    name: 'Global X Robotics & AI ETF',
    category: 'Thematic & Growth',
    issuer: 'Global X',
    currency: 'USD',
    exchange: 'NASDAQ',
    price: 33.20,
    changePct: 1.45,
    change: 0.47,
    nav: 33.18,
    aum: 2850000000,
    aumFormatted: '$2.85B',
    volume: 1400000,
    avgVolume: 1600000,
    expenseRatio: 0.68,
    dividendYield: 0.22,
    distributionFrequency: 'Semi-Annual',
    beta: 1.35,
    sharpeRatio: 1.42,
    trackingError: 0.07,
    return1y: 31.8,
    return3y: 10.5,
    return5y: 14.8,
    inceptionDate: '2016-09-12',
    fiftyTwoWeekHigh: 35.40,
    fiftyTwoWeekLow: 25.80,
    benchmarkIndex: 'Indxx Global Robotics & Artificial Intelligence Thematic Index',
    holdingsCount: 44,
    topHoldings: [
      { symbol: 'NVDA', name: 'NVIDIA Corp.', weight: 12.4 },
      { symbol: 'ISRG', name: 'Intuitive Surgical Inc.', weight: 10.5 },
      { symbol: 'ABB', name: 'ABB Ltd.', weight: 8.4 },
      { symbol: 'FANUY', name: 'Fanuc Corp ADR', weight: 6.5 }
    ],
    sectorWeights: [
      { sector: 'Robotics & Automation', weight: 42.5 },
      { sector: 'Artificial Intelligence', weight: 38.2 },
      { sector: 'Industrial Machinery', weight: 19.3 }
    ],
    description: 'Robotik otomasyon, cerrahi robotlar ve endüstriyel yapay zeka teknolojileri fonu.'
  },

  // 8. GLOBAL & EMERGING MARKETS
  {
    ticker: 'VXUS',
    name: 'Vanguard Total International Stock ETF',
    category: 'Global & Emerging',
    issuer: 'Vanguard',
    currency: 'USD',
    exchange: 'NASDAQ',
    price: 64.80,
    changePct: 0.35,
    change: 0.22,
    nav: 64.78,
    aum: 72400000000,
    aumFormatted: '$72.4B',
    volume: 3800000,
    avgVolume: 4200000,
    expenseRatio: 0.07,
    dividendYield: 3.15,
    distributionFrequency: 'Quarterly',
    beta: 0.85,
    sharpeRatio: 0.98,
    trackingError: 0.03,
    return1y: 16.8,
    return3y: 4.8,
    return5y: 6.8,
    inceptionDate: '2011-01-26',
    fiftyTwoWeekHigh: 66.20,
    fiftyTwoWeekLow: 54.80,
    benchmarkIndex: 'FTSE Global All Cap ex US Index',
    holdingsCount: 8500,
    topHoldings: [
      { symbol: 'TSM', name: 'Taiwan Semiconductor', weight: 2.15 },
      { symbol: 'NVO', name: 'Novo Nordisk A/S', weight: 1.85 },
      { symbol: 'ASML', name: 'ASML Holding NV', weight: 1.65 },
      { symbol: 'NESN', name: 'Nestle SA', weight: 1.25 }
    ],
    sectorWeights: [
      { sector: 'Financials', weight: 21.4 },
      { sector: 'Industrials', weight: 16.8 },
      { sector: 'Technology', weight: 13.5 }
    ],
    description: 'ABD dışındaki tüm gelişmiş ve gelişmekte olan ülkelerden 8.500 şirketi içeren küresel çeşitlendirme fonu.'
  },
  {
    ticker: 'INDA',
    name: 'iShares MSCI India ETF',
    category: 'Global & Emerging',
    issuer: 'BlackRock / iShares',
    currency: 'USD',
    exchange: 'NYSE Arca',
    price: 58.20,
    changePct: 0.75,
    change: 0.43,
    nav: 58.18,
    aum: 10500000000,
    aumFormatted: '$10.5B',
    volume: 3200000,
    avgVolume: 3600000,
    expenseRatio: 0.64,
    dividendYield: 0.45,
    distributionFrequency: 'Semi-Annual',
    beta: 0.72,
    sharpeRatio: 1.55,
    trackingError: 0.06,
    return1y: 32.5,
    return3y: 14.8,
    return5y: 16.2,
    inceptionDate: '2012-02-02',
    fiftyTwoWeekHigh: 60.50,
    fiftyTwoWeekLow: 44.20,
    benchmarkIndex: 'MSCI India Index',
    holdingsCount: 145,
    topHoldings: [
      { symbol: 'RELIANCE', name: 'Reliance Industries Ltd.', weight: 8.5 },
      { symbol: 'HDFCBANK', name: 'HDFC Bank Ltd.', weight: 7.2 },
      { symbol: 'ICICIBANK', name: 'ICICI Bank Ltd.', weight: 6.4 },
      { symbol: 'INFOSYS', name: 'Infosys Ltd.', weight: 5.8 },
      { symbol: 'TCS', name: 'Tata Consultancy Services', weight: 4.2 }
    ],
    sectorWeights: [
      { sector: 'Financials', weight: 26.4 },
      { sector: 'Technology', weight: 14.8 },
      { sector: 'Energy', weight: 12.5 },
      { sector: 'Consumer Cyclical', weight: 11.2 }
    ],
    description: 'Dünyanın en hızlı büyüyen büyük ekonomisi Hindistanın önde gelen 140+ şirketine yatırım fonu.'
  }
];
